baseURL         = "https://macfinter.github.io/"
languageCode    = "ru-ru"
title           = "Блог по Quarkus in Action"
theme           = "tranquilpeak"

canonifyURLs    = true

# из exampleSite/config.toml :contentReference[oaicite:0]{index=0}
[[menu.main]]
name       = "Home"
url        = "/"
weight     = 1

[[menu.main]]
name       = "Categories"
url        = "/categories"
weight     = 2

[[menu.main]]
name       = "Tags"
url        = "/tags"
weight     = 3

[[menu.main]]
name       = "Archives"
url        = "/archives"
weight     = 4

[[menu.main]]
name       = "About"
url        = "/#about"
weight     = 5
