baseURL = "https://macfinter.github.io/my-quarkus-in-action-blog/"
languageCode = "ru-ru"
title = "Блог по Quarkus in Action"
theme = "tranquilpeak"
relativeURLs = true

googleAnalytics = ""

[params]
subtitle = "Конспекты и примеры из книги на русском"